<?php

/**
* Model stub class generated by the Wave\DB ORM.
* Changes made to this file WILL NOT BE OVERWRITTEN when database is next generated.
*
* @package:   Models\Models\Auth
* @generated: 2015-09-28 08:02:32
*
* @schema:    service-auth
* @table:     access_token
* @engine:    InnoDB
* @collation: utf8_general_ci
*
*/

namespace Models\Platform;

use DateTime;
use Helpers\RandomStringHelper;
use Wave,
    Wave\DB;
use Wave\Config;

class AuthToken extends Base\AuthToken {

    /**
     * Creates an access token object and returns the corresponding random string.
     *
     * @param User $user
     * @return bool|string
     *
     */
    public static function create(User $user){

        $config = Config::get('app')->auth;

        $validity = (isset($config['access_token_validity']) ? $config['access_token_validity'] : '+3 hours');

        $params['user_id'] = $user->user_id;
        $params['issued'] = new DateTime();
        $params['expires'] = new DateTime($validity);
        $params['access_token'] = RandomStringHelper::getString();
        $params['additional_data'] = $data;

        $token = new AccessToken();
        $token->updateFromArray($params);

        $token->save();

        return $token->access_token;

    }

    /**
     * @param $access_token
     * @return array|null|DB\Model
     * @throws DB\Exception
     * @throws Wave\Exception
     *
     * Loads any valid (not revoked, not expired) token that matches the acess token
     *
     */
    public static function load_valid_by_token($access_token) {

        $now = new DateTime();

        return DB::get()->from('AccessToken')
            ->where('access_token = ?', $access_token)
            ->and('revoked = ?', false)
            ->and('expires > ? ', $now)
            ->fetchRow();

    }

    public function getCompiledToken(){

        $t = $this->_toArray();
        $t['client'] = $this->Client;

        return $t;

    }

    public function getadditional_data()
    {
        $string = parent::getadditional_data();

        if($string !== null && $string !== '') {
            $data = json_decode($string, true);

            if(json_last_error() == JSON_ERROR_NONE)
                return $data;
        }

        return [];
    }

    /**
     * @return array|mixed
     *
     * Set additional data that will be re-set on any new
     * access tokens created by this refresh token
     *
     */
    public function setadditional_data($data = array())
    {

        if(is_array($data) === false){
            $data = [];
        }

        $string = json_encode($data);

        return parent::setadditional_data($string);
    }

    /**
     *
     * Revokes an active token - making it useless.
     *
     */
    public static function revoke($user_id, $client_id) {

        $now = new DateTime();

        $tokens = DB::get()->from('AccessToken')
            ->where('user_id = ?', $user_id)
            ->where('client_id = ?', $client_id)
            ->where('revoked = ?', false)
            ->where('expires > ?', $now)
            ->fetchAll();

        /** @var AccessToken $token */
        foreach ($tokens as $token){
            $token->revoked = true;
            $token->save();

            // Cache bust
            Cache::delete('/auth/access-token/' . $token->access_token);
        }

    }

}

