<?php

/**
* Model stub class generated by the Wave\DB ORM.
* Changes made to this file WILL NOT BE OVERWRITTEN when database is next generated.
*
* @package:   Models\Models\Platform
* @generated: 2018-05-12 07:51:13
*
* @schema:    site
* @table:     phinxlog
* @engine:    InnoDB
* @collation: utf8_general_ci
*
*/

namespace Models\Platform;

class Phinxlog extends Base\Phinxlog {

}