#!/bin/bash

conman config --role='api-mobile' --realm="$1" > scaffold/conman.json

[[ $1 = 'rancher' ]] && prod_mode="true" || prod_mode="false"

docker build --pull -t git.dev.hellpizza.com:5555/styx/server/api-mobile:$CI_COMMIT_REF_NAME --build-arg newrelic_enabled=$prod_mode --file api-mobile/Dockerfile .
docker push git.dev.hellpizza.com:5555/styx/server/api-mobile:$CI_COMMIT_REF_NAME